name: 'Execute gradle tasks'
description: 'Execute tasks and report statuses'
inputs:
  variant:
    description: 'Build variant to use'
    required: false
    default: 'Release'
  test:
    description: 'Are unit tests to run?'
    required: false
    default: false
  lint:
    description: 'Is linter to run?'
    required: false
    default: false
  build:
    description: 'Are APKs to build?'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Prepare
      shell: bash
      run: |
        export CHECK_RUN_SHA=${{ github.event.pull_request.head.sha }}
        echo "CHECK_RUN_SHA=$CHECK_RUN_SHA" >>$GITHUB_ENV
        [[ '${{ inputs.test }}' == 'true' ]] && ${{ github.action_path }}/run-as-check.sh "Unit Tests (${{ inputs.variant }})" --queued || :
        [[ '${{ inputs.lint }}' == 'true' ]] && ${{ github.action_path }}/run-as-check.sh "Lint (${{ inputs.variant }})" --queued || :
        [[ '${{ inputs.build }}' == 'true' ]] && ${{ github.action_path }}/run-as-check.sh "Build APK (${{ inputs.variant }})" --queued || :

    - name: Run Unit Tests
      if: ${{ inputs.test == 'true' }}
      shell: bash
      continue-on-error: true
      run: |
        ${{ github.action_path }}/run-as-check.sh "Unit Tests (${{ inputs.variant }})" \
          './gradlew test${{ inputs.variant }}UnitTest'

    - name: Run Linter
      if: ${{ inputs.lint == 'true' }}
      shell: bash
      continue-on-error: true
      run: |
        ${{ github.action_path }}/run-as-check.sh "Lint (${{ inputs.variant }})" \
          './gradlew lint${{ inputs.variant }}'

    - name: Build APKs
      id: build-apks
      if: ${{ inputs.build == 'true' }}
      shell: bash
      continue-on-error: true
      run: |
        ${{ github.action_path }}/run-as-check.sh "Build APK (${{ inputs.variant }})" \
          './gradlew assemble${{ inputs.variant }}'

    - name: Pack APKs
      id: pack-apks
      if: ${{ steps.build-apks.outcome == 'success' }}
      shell: bash
      run: |
        tar -cvf outputs-apk-${{ inputs.variant }}.tar */build/outputs/apk/

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      if: ${{ steps.pack-apks.outcome == 'success' }}
      with:
        name: outputs-apk-${{ inputs.variant }}.tar
        path: outputs-apk-${{ inputs.variant }}.tar
