name: 'Execute gradle tasks'
description: 'Execute tasks and report statuses'
inputs:
  variant:
    description: 'Build variant to use'
    required: false
    default: 'Release'
  test:
    description: 'Are unit tests to run?'
    required: false
    default: false
  lint:
    description: 'Is linter to run?'
    required: false
    default: false
  build:
    description: 'Are APKs to build?'
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: Prepare
      shell: bash
      run: |
        if [[ '${{ github.event_name }}' == 'push' ]] ; then
          COMMIT_SHA="${{ github.sha }}"
        elif [[ '${{ github.event_name }}' == 'pull_request' ]] ; then
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
        else
          echo "Unsupported event: '${{ github.event_name }}'"
          exit 1
        fi
        echo "COMMIT_SHA=$COMMIT_SHA" >>$GITHUB_ENV

    - name: Run Unit Tests
      id: run-unit-tests
      if: ${{ inputs.test == 'true' }}
      shell: bash
      continue-on-error: true
      run: |
        ${{ github.action_path }}/run-with-status.sh "Unit Tests (${{ inputs.variant }})" \
          './gradlew test${{ inputs.variant }}UnitTest'

    - name: Run Linter
      id: run-linter
      if: ${{ inputs.lint == 'true' }}
      shell: bash
      continue-on-error: true
      run: |
        ${{ github.action_path }}/run-with-status.sh "Lint (${{ inputs.variant }})" \
          './gradlew lint${{ inputs.variant }}'

    - name: Build APKs
      id: build-apks
      if: ${{ inputs.build == 'true' }}
      shell: bash
      continue-on-error: true
      run: |
        ${{ github.action_path }}/run-with-status.sh "Build APK (${{ inputs.variant }})" \
          './gradlew assemble${{ inputs.variant }}'

    - name: Pack APKs
      id: pack-apks
      if: ${{ steps.build-apks.outcome == 'success' }}
      shell: bash
      run: |
        tar -cvf outputs-apk-${{ inputs.variant }}.tar */build/outputs/apk/

    - name: Upload APKs
      id: upload-apks
      uses: actions/upload-artifact@v4
      if: ${{ steps.pack-apks.outcome == 'success' }}
      with:
        name: outputs-apk-${{ inputs.variant }}.tar
        path: outputs-apk-${{ inputs.variant }}.tar

    - name: Conclusion
      shell: bash
      run: |
        [[ ${{ steps.run-unit-tests.outcome }} != 'failure' ]] \
          && [[ ${{ steps.run-linter.outcome }} != 'failure' ]] \
          && [[ ${{ steps.build-apks.outcome }} != 'failure' ]] \
          && [[ ${{ steps.pack-apks.outcome }} != 'failure' ]] \
          && [[ ${{ steps.upload-apks.outcome }} != 'failure' ]] \
