name: 'Run Tests'
description: 'Run tests indeed'
inputs:
  PLATFORM:
    type: string
    required: true
  TEST:
    type: string
    required: true

runs:
  using: "composite"

  steps:
    - name: Prepare
      shell: bash {0}
      run: |
        echo "step 2 on ${{ inputs.PLATFORM }} for ${{ inputs.TEST }}"

    - name: Run Tests
      shell: bash {0}
      run: |
        echo "step 2 on ${{ inputs.PLATFORM }} for ${{ inputs.TEST }}"
