# This is a basic workflow to help you get started with Actions
name: Run On All Platforms

on:
  workflow_call:
    inputs:
      CONFIG_JSON:
        required: true
        type: string

jobs:
  platform-work-1:
    name: Platform P1
    if: ${{ !cancelled() && fromJSON(inputs.CONFIG_JSON).P1 != '' }}
    uses: ./.github/workflows/platform.yml
    with:
      platform: P1
      tests: ${{ toJSON(fromJSON(inputs.CONFIG_JSON).P1) }}
  
  platform-work-2:
    name: Platform P2
    if: ${{ !cancelled() && fromJSON(inputs.CONFIG_JSON).P2 != '' }}
    uses: ./.github/workflows/platform.yml
    with:
      platform: P2
      tests: ${{ toJSON(fromJSON(inputs.CONFIG_JSON).P2) }}
