# This is a basic workflow to help you get started with Actions

name: Big One

on:
  workflow_dispatch:
    inputs:
      PLATFORM:
        type: string
        description: 'Platform'
        required: false
        default: AAA

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo "The Preparation It Is"
          echo "::notice title=Runner Is Selected::Yes it was"
  
  platform-work-1:
    name: Platform (${{ inputs.PLATFORM }})-1
    needs: preparation
    uses: ./.github/workflows/platform.yml
    with:
      platform: ${{ inputs.PLATFORM }}-1
      tests: '{"include":[{"test":"p1-first"}, {"test":"p1-second"}]}'
  
  platform-work-2:
    name: Platform (${{ inputs.PLATFORM }})-2
    needs: preparation
    uses: ./.github/workflows/platform.yml
    with:
      platform: ${{ inputs.PLATFORM }}-2
      tests: '{"include":[{"test":"p2-first"}, {"test":"p2-second"}]}'
  