# This is a basic workflow to help you get started with Actions

name: Big One

on:
  workflow_dispatch:
    inputs:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        variant: [debug, release, releaseSyte]
    steps:
      - run: |
          echo "Prepare ${{ matrix.variant }}..."
      
      - run: |
          OUTPUT_DIR='./build/outputs/apk/${{ matrix.variant }}'
          mkdir -p $OUTPUT_DIR
          echo "content of ${{ matrix.variant }} build" >$OUTPUT_DIR/text.txt
          tar -cvf ./outputs-apk.tar $OUTPUT_DIR

      - uses: actions/upload-artifact@v4
        with:
          name: outputs-apk-${{ matrix.variant }}.tar
          path: ./outputs-apk.tar

  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: outputs-apk-*.tar
          merge-multiple: true
          path: ./tmp/
