# This is a basic workflow to help you get started with Actions

name: Big One

on:
  workflow_dispatch:
    inputs:
      PLATFORM:
        type: string
        description: 'Platform'
        required: false
        default: AAA

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: |
          echo "The Preparation It Is"
          echo "::notice title=Runner Is Selected::Yes it was"

  platform-work:
    name: Platform Work
    needs: preparation
    strategy:
      matrix:
        platform: [PLATF-1, PLATF-2]
    uses: ./.github/workflows/platform.yml
    with:
      platform: ${{ matrix.platform }}
      tests: '{"include":[{"test":"${{ matrix.platform }}-first"}, {"test":"${{ matrix.platform }}-second"}]}'
