# This is a basic workflow to help you get started with Actions

name: Big One

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      DRY_RUN:
        type: boolean
        description: 'Make it dry'
        required: false
        default: false
      PLATFORM:
        type: string
        description: 'Platform'
        required: false
        default: AAA

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "The Preparation It Is"
  
  platform-work:
    name: Platform (${{ inputs.PLATFORM }})
    needs: preparation
    uses: ./.github/workflows/platform.yml
    with:
      platform: ${{ inputs.PLATFORM }}
      dry_run: ${{ inputs.DRY_RUN }}
      tests: '{"include":[{"test":"first"}, {"test":"second"}]}'
  
#   platform-work-2:
#     needs: preparation
#     uses: ./.github/workflows/platform.yml
#     with:
#       platform: BBB
#       tests: '{"include":[{"test":"first"}, {"test":"second"}]}'
  
#   platform-work-3:
#     needs: preparation
#     uses: ./.github/workflows/platform.yml
#     with:
#       platform: CCC
#       tests: '{"include":[{"test":"first"}, {"test":"second"}, {"test":"third"}]}'
