# This is a basic workflow to help you get started with Actions

name: Big One

on:
  workflow_dispatch:
    inputs:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        variant: [debug, release, releaseSyte]
    permissions:
      statuses: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gradle-build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          variant: ${{ matrix.variant }}
          build: true

  publish:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: outputs-apk-*.tar
          merge-multiple: true
          path: ./tmp/
      - run: |
          ls -lah 
          tar -xf ./tmp/*.tar
          ls -lah ./
          ls -lah ./build/outputs/apk
