# This is a basic workflow to help you get started with Actions

name: Big One

on:
  workflow_dispatch:
    inputs:

jobs:
  preparation:
    runs-on: ubuntu-latest
    outputs:
      CONFIG_JSON_S1: ${{ steps.generate-config-json.outputs.CONFIG_JSON_S1 }}
      CONFIG_JSON_S2: ${{ steps.generate-config-json.outputs.CONFIG_JSON_S2 }}
    steps:
      - name: Run a one-line script
        id: generate-config-json
        run: |
          echo "The Preparation It Is"
          echo "::notice title=Runner Is Selected::Yes it was"
          echo 'CONFIG_JSON_S1={"P1":{"include":[{"test":"p1-first"}, {"test":"p1-second"}]}, "P2":{"include":[{"test":"p2-first"}, {"test":"p2-second"}]}}' >>$GITHUB_OUTPUT
          echo 'CONFIG_JSON_S2={"P2":{"include":[{"test":"p2-first"}, {"test":"p2-second"}]}}' >>$GITHUB_OUTPUT
      - name: Log It
        run: |
          echo -e "CONFIG_JSON_S1:\n${{ steps.generate-config-json.outputs.CONFIG_JSON_S1 }}\n"
          echo -e "CONFIG_JSON_S2:\n${{ steps.generate-config-json.outputs.CONFIG_JSON_S2 }}\n"

  stage-1:
    name: Stage 1
    needs: preparation
    uses: ./.github/workflows/_all_platforms_run.yml
    if: ${{ needs.preparation.outputs.CONFIG_JSON_S1 != '' }}
    with:
      CONFIG_JSON: ${{ needs.preparation.outputs.CONFIG_JSON_S1 }}

  stage-2:
    name: Stage 2
    needs: [preparation, stage-1]
    uses: ./.github/workflows/_all_platforms_run.yml
    if: ${{ needs.preparation.outputs.CONFIG_JSON_S2 != '' }}
    with:
      CONFIG_JSON: ${{ needs.preparation.outputs.CONFIG_JSON_S2 }}