# This is a basic workflow to help you get started with Actions
name: Prepare And Run

on:
  workflow_call:
    inputs:
      PLATFORM:
        required: true
        type: string
      TESTS:
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Prepare workflow=${{ github.workflow }}. PLATFORM=${{ inputs.PLATFORM }}, TESTS=${{ inputs.TESTS }}"

  run:
    runs-on: ubuntu-latest
    needs: prepare
    if: success() && inputs.TESTS != ''
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.TESTS) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Run Indeed
        uses: ./.github/actions/run-tests
        with:
          PLATFORM: ${{ inputs.PLATFORM }}
          TEST: ${{ matrix.test }}
