# This is a basic workflow to help you get started with Actions
name: Platform Job

on:
  workflow_call:
    inputs:
      PLATFORM:
        required: true
        type: string
      TESTS:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      PLATFORM:
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Prepare on ${{ inputs.PLATFORM }}"

  run:
    needs: prepare
    if: success() && inputs.TESTS != ''
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.TESTS) }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Indeed
        uses: ./.github/actions/run-tests
        with:
          PLATFORM: ${{ inputs.PLATFORM }}
