# This is a basic workflow to help you get started with Actions
name: Prepare And Run

on:
  workflow_call:
    inputs:
      PLATFORM:
        required: true
        type: string
      TESTS:
        required: true
        type: string
      DRY_RUN:
        required: false
        type: boolean
        default: false
  workflow_dispatch:
    inputs:
      PLATFORM:
        required: true
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Prepare on ${{ inputs.PLATFORM }}, workflow=${{ github.workflow }}"

  run:
    needs: prepare
    if: success() && inputs.TESTS != ''
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.TESTS) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Run Indeed
        uses: ./.github/actions/run-tests
        with:
          PLATFORM: ${{ inputs.PLATFORM }}
          DRY_RUN: ${{ fromJSON(inputs.DRY_RUN) }}
