# This is a basic workflow to help you get started with Actions

name: Starter

on:
  workflow_dispatch:
    inputs:

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue title" --body "Issue body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
