name: Tests
on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_message=${{ toJSON(github.event.pull_request.body) }}
          echo -e "PR message:\n$pr_message\n----------"
          if [[ "$pr_message" == *"[auto-merge]"* ]]; then
            echo "Auto-merge enabled"
            gh pr merge --repo ${{ github.repository }} \
              ${{ github.event.number }} --auto --squash
          else
            echo "Auto-merge not enabled"
          fi
      - name: Fake Tests
        run: |
          sleep 3
          echo 'I am OK with that'
